server:
  port: 1006
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: DEmart


    
    
#given name 
  application:
    name: DEmart-OrderCartWishListService
    


logging:
  level:
    org.springframework.data.mongodb.core: DEBUG
    
    
    

    
#EUREKA CONFIGURATION

eureka:
  instance:
    prefer-ip-address: true
  client: 
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka