server:
  port: 1001
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demart
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    


    
    
#given name 
  application:
    name: DEmart-BrandService
    
    
    
    
    

    
#EUREKA CONFIGURATION

eureka:
  instance:
    prefer-ip-address: true
  client: 
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka