  
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/DEmart-Ecom
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    
    
    
#given name 
  application:
    name: DEmart-ProductService
    
    
    
#EUREKA CONFIGURATION

#eureka:
#  instance:
#    prefer-ip-address: true
#  client: 
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka